const ADD_INGREDIENT = 'ADD_INGREDIENT';
const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
const SET_INGREDIENTS = 'SET_INGREDIENTS';
const SET_FETCH_ERROR = 'SET_FETCH_ERROR'


export {ADD_INGREDIENT, REMOVE_INGREDIENT, SET_INGREDIENTS, SET_FETCH_ERROR}